# SAM configuration file for Christopher Corbin Portfolio

version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "christopher-corbin-portfolio-backend"
s3_prefix = "christopher-corbin-portfolio-backend"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
parameter_overrides = "ContactEmail=\"christophercorbin24@gmail.com\""
resolve_s3 = true
image_repositories = []

[default.build]
[default.build.parameters]
cached = true
parallel = true