name: Deploy SAM Application

on:
  push:
    branches: [ main ]
    paths:
      - 'template.yaml'
      - 'src/**'
      - 'samconfig.toml'
  workflow_dispatch:

jobs:
  deploy-sam:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Setup AWS SAM CLI
      uses: aws-actions/setup-sam@v2
      with:
        use-installer: true
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Build SAM application
      run: sam build
    
    - name: Validate required secrets
      run: |
        if [[ -z "${{ secrets.CONTACT_EMAIL }}" ]]; then
          echo "❌ Error: CONTACT_EMAIL secret is not set"
          echo "Please add CONTACT_EMAIL to your GitHub repository secrets"
          exit 1
        fi
        echo "✅ CONTACT_EMAIL secret is configured"
        
        # Set default CORS origin if not provided
        CORS_ORIGIN="*"
        if [[ -n "${{ secrets.CLOUDFRONT_DOMAIN }}" ]]; then
          CORS_ORIGIN="https://${{ secrets.CLOUDFRONT_DOMAIN }}"
        fi
        echo "CORS_ORIGIN=$CORS_ORIGIN" >> $GITHUB_ENV
    
    - name: Deploy SAM application
      run: |
        sam deploy \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --stack-name christopher-corbin-portfolio-backend \
          --capabilities CAPABILITY_IAM \
          --region us-east-1 \
          --parameter-overrides \
            "ContactEmail=${{ secrets.CONTACT_EMAIL }}" \
            "CorsOrigin=$CORS_ORIGIN"
    
    - name: Get and display API Gateway URL
      run: |
        echo "⏳ Retrieving API Gateway URL..."
        API_URL=$(aws cloudformation describe-stacks \
          --stack-name christopher-corbin-portfolio-backend \
          --region us-east-1 \
          --query 'Stacks[0].Outputs[?OutputKey==`ContactApiUrl`].OutputValue' \
          --output text)
        
        if [[ -n "$API_URL" && "$API_URL" != "None" ]]; then
          echo "✅ Contact API URL: $API_URL"
          echo "🚀 Your contact form backend is now live!"
        else
          echo "⚠️ Warning: Could not retrieve API URL"
        fi
